### ISSUE TITLE
[Feature Request]: add typescript definition file.

### ISSUE THREAD

**Issue by chanlito** [ianstormtaylor/permit#11]
I know that permit has a small set of api, but a Typescript definition file wouldn't hurt right? 😜

**Comment by ianstormtaylor** [comment]
Hey @chanlito, I'm all for people using Permit in TypeScript, but I'd ask that any type definitions be added to Definitely Typed (or whatever the best practice is), because I don't personally use TypeScript so I can't commit to keep the definitions up to date over time. I hope that makes sense. Thanks for opening this!
